apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: branch-tls-external
  labels:
    cert-manager.io/solver: http01
spec:
  commonName: "*.branch.sas-notprod.homeoffice.gov.uk"
  dnsNames:
  - "*.branch.sas-notprod.homeoffice.gov.uk"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: branch-tls-external
